spring:
  data:
    mongodb:
      uri: mongodb+srv://testingacc9756:blg8QXcCuPRUxj5G@cluster0.hkcfd.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      auto-index-creation: true
      database: journaldb


server:
  port: 8080
  servlet:
    context-path: /journal

    weather:
      api:
        key: 59247bf67d64e793ebcc4d6812f5fd7d

weather.api.key: 59247bf67d64e793ebcc4d6812f5fd7d